### ISSUE TITLE
Events API call returns old events

### ISSUE THREAD

**Issue by bacharakis** [lambdaspace/LambdaSpaceAPIv2#10]
[Events call](https://api.lambdaspace.gr/api/v2.0/events) returns old events.

**Comment by panagiks** [comment]
So does discource's API (from which we draw them). This can be resolved with a limit, after #9 is done.  

I personally think this is a noop as the EP is called `events` and not `future_events` or `/events/future`. It would probably be best that we add another EP for future events.

Also a simple filter on the consumer `if obj.date < today pass` would do the job.

**Comment by alexdor** [comment]
@panagiks events from the [discourse API](https://community.lambdaspace.gr/c/events.json) seems fine to me
